Fix a compile error on Mac OS X 10.6.6.
The exact error was:

Solver.cpp: In member function ‘Clause* Solver::analyze(PropBy, vec<Lit>&,
int&, uint32_t&, bool)’:
Solver.cpp:1129: error: no matching function for call to
‘PropByFull::PropByFull(PropByFull)’
PropBy.h:211: note: candidates are: PropByFull::PropByFull(PropByFull&)

and it occurred with the follow versions of GCC:

 * 4.2.1 (Apple Inc. build 5664)
 * 4.3.5 (from MacPorts)
 * 4.5.2 (from MacPorts)

I could not reproduce the error on Ubuntu 9.04 with GCC 4.3.3-5ubuntu4 or on
Ubuntu 10.10 with GCC 4.4.4-14ubuntu5, so this looks like an OS-X-only issue.